### ISSUE TITLE
Qibosoq executables

### ISSUE THREAD

**Issue by rodolfocarobene** [qiboteam/qibosoq#12]
Following the discussion in #11:

> the actual execution makes your package an application, but it is rather weird if you then deploy it as a package: how would you run after installing with pip install qibosoq? (solution python /path/to/env/lib/python3.x/site-packages/qibosoq/rfsoc_server.py... not the best...)

I think we could also add, linked to this problem, executables like qibocal has (`qq`, `qq-auto`...)

**Comment by AleCandido** [comment]
For this, you can add in the package information: usually the packaging framework (e.g. both setuptools and Poetry) have a field for mapping between an executable name and a function in your package.

However, for as long as you have a single entry point with no argument, `python -m qibosoq` is perfect.
The moment you will add a more complex CLI (arguments, subcommands, ...) we can use suitable tools (e.g. `click`, as CLI framework, and entry points declaration).

**Comment by rodolfocarobene** [comment]
Also closing the server that is running in background is now a bit difficult since it requires to find the PID of the python process and to kill it

**Comment by AleCandido** [comment]
You can use `nohup` instead of `disown` to have a single command.

However, in principle, the only difference in what you're saying is that `server-run` is replaced by `python -m qibosoq`.
Since for `python -m` you need nothing, and it will work in develop and production mode out of the box, I suggest to start with that. If you want to immediately run with a single command, just add somewhere:
```
alias server-run="python -m qibosoq"
```

Everything else (arguments and redirect) is the exact same with `__main__.py` and an actual CLI, and you can properly solve using `argparse` or `click` (or even parsing arguments manually from `sys.argv`, definitely not recommended).
I'm just suggesting to postpone this step, since it is not really a priority and it has an over-head in development.

**Comment by AleCandido** [comment]
> Also closing the server that is running in background is now a bit difficult since it requires to find the PID of the python process and to kill it

This is again the same in both cases, and if you search, you can search for both. It also has a simple solution: log the PID (i.e. `os.getpid()`).

**Comment by rodolfocarobene** [comment]
Closing this, following merge of #11
