### ISSUE TITLE
Unexpected error that I can't reproduce(?)

### ISSUE THREAD

**Issue by rodolfocarobene** [qiboteam/qibosoq#40]
Hello @stavros11 @AleCandido, sorry to bother you but I need your expertise :-)
Is this line wrong for some reason?

https://github.com/qiboteam/qibosoq/blob/2e46ec70af79d04dcd747b3f8ead0ed9c3989a74/src/qibosoq/qick_programs.py#L463

I was getting an error from this line saying that `Sweeper object is not iterable` so I stopped the server, added some log.info before (printing sweepers and type(sweepers) I think) and the error disappeared. Than I removed the log.info and now there is no error...
Is this line of code "unsafe" for some reason or have you any idea of why/how something like this could have happened?

**Comment by AleCandido** [comment]
I believe there is nothing unsafe, after that line `self.sweepers` is a list.

However, we should have a look at the history. For sure, one effect of adding the log.info was uploading a new version of the server, so, the problem could have been only in a previous version.

The best thing you can do to ensure this, it's definitely splitting in smaller functions and adding a unit test checking that is actually always a list.
This will give you more confidence, and keep checking the assertion even when further changes will be added.

**Comment by AleCandido** [comment]
The only tiny, unrelated, improvement to that line could be to turn `list(sweepers)[::-1]` into `list(reversed(sweepers))`.

Working with iterators is lazy, because the iteration of the input doesn't actually happen until you iterate the output. For this reason, you could concatenate multiple functions on iterators and eventually iterate just once.

Instead, working with lists is eager, since every time you turn a list into another list you have to actually iterate it.

But given the performances of Python, this is a second order problem (but given that it is simple, I would fix it anyhow).

**Comment by rodolfocarobene** [comment]
thank you @AleCandido , I opened a PR with a new function and its test (#41).
This was really a weird error and I am pretty sure that the running server didn't change...

**Comment by AleCandido** [comment]
Then it should come from somewhere else. Unfortunately, until you can't reproduce, there is almost nothing we could do about a little known error 😞
