### ISSUE TITLE
Add workflows

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibosoq#5]
Ideally, we would like to deploy this package to pypi so qibolab can rely on that for quick.

**Comment by rodolfocarobene** [comment]
Hello @scarrazza, I was adding some documentation with sphinx here #10.
@Edoardo-Pedicillo explained to me that, to deploy it automatically, we need to create a new environment in the settings of the website (or something like that, I'm not completely sure). 

Should we add qibosoq to the website, or is it better to wait for now? And, eventually, how is it done?

**Comment by scarrazza** [comment]
@rodolfocarobene indeed, please have a chat with @MatteoRobbiati and @Edoardo-Pedicillo in order to extend the webpage template and introduce the new workflow.

**Comment by Edoardo-Pedicillo** [comment]
> What do you mean by "a new environment"?

If we want to use the Github pages we have to able it in the setting (@rodolfocarobene for more information you can see [here](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)) and eventually define some protection rules in the `github-pages` environment. I don't have the permission to do it, but we can discuss the deployment and for any issue I can help you.

**Comment by AleCandido** [comment]
Ah ok, that's reasonable. The exact link is:
https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow

This is because we use the non-default procedure of using GitHub Actions to directly deploy (non-default because new, but rather encouraged by GitHub).

About branch protections rules, I'm not aware of anything that is needed. In particular, we do *not* use a `github-pages` branch, since we're deploying with Actions.

**Comment by rodolfocarobene** [comment]
So, for what I understand, it makes sense to first merge #10 (that also has the `publish.yml` action) and then add the workflow through settings (that I don't have the permission to access). Is it correct?

**Comment by AleCandido** [comment]
Not exactly: the `publish.yml` is the workflow, and it is already active as soon as it's committed and pushed.

What you would have to enable from the Settings tab is just the deployment: at the moment, the workflow would do everything is expected to (if there are no further issues), and then just fail at the very end, since it would not be allowed to deploy the compiled docs.

However, keep going. There would be nothing bad in failing at the end, we can make sure from the logs whether all the other steps succeeded or not (and in principle it should even upload the compiled docs in an artifact, before failing, so we should be able to download and check).

In the meanwhile, it might happen that @scarrazza will enable the deployment from GitHub Actions :)

**Comment by rodolfocarobene** [comment]
@scarrazza I think that there is still some problem with the documentation deployment. 
The action works, but then the docs are not available anywhere

**Comment by scarrazza** [comment]
Are you sure https://qibo.science/qibosoq/stable/?

**Comment by rodolfocarobene** [comment]
Oh, I was looking at https://qibo.science/qibosoq ... thank you!
